//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Script
{
    using System;
    using System.Xml;
    using System.Xml.Schema;
    using System.Collections.Generic;
    using HP.ST.Fwk.RunTimeFWK;
    using HP.ST.Fwk.RunTimeFWK.CheckpointFWK;
    using HP.ST.Fwk.RunTimeFWK.Utilities;
    using HP.ST.Ext.CheckpointLogicOperators;
    using HP.ST.Ext.BindingImpl.Getters;
    using HP.ST.Ext.BindingImpl.Setters;
    using HP.ST.Fwk.RunTimeFWK.BindingFWK;
    using HP.ST.Fwk.RunTimeFWK.BindingFWK.Getters;
    using HP.ST.Fwk.RunTimeFWK.BindingFWK.Setters;
    using HP.ST.Fwk.RunTimeFWK.BindingFWK.PropInfo;
    using HP.ST.Ext.CheckpointRules;
    using HP.ST.Ext.CheckpointRules.ArrayCheckpoints;
    
    
    public partial class WorkFlowScript
    {
        
        private void set_StServiceCallActivity4_checkpoints(STActivityBase activity)
        {
            VTDPropertyInfoBase stracturalOutputEnvelope = new VTDPropertyInfoBase("OutputEnvelope", "/*[local-name(.)=\'Envelope\'][1]");
            IList<VTDPropertyInfoBase> stracturalPropsInfo = new List<VTDPropertyInfoBase>();
            CpValObj ExpectedSchema = new CpValObj("<?xml version=\"1.0\" encoding=\"utf-16\"?><xs:schema xmlns=\"http://schemas.xmlsoap.o" +
                    "rg/soap/envelope/\" xmlns:vtd=\"hp.visual_test_designer\" elementFormDefault=\"quali" +
                    "fied\" targetNamespace=\"http://schemas.xmlsoap.org/soap/envelope/\" xmlns:xs=\"http" +
                    "://www.w3.org/2001/XMLSchema\"><xs:import schemaLocation=\"EmbeddedResources/Fligh" +
                    "ts_SO\\webServices\\Flights_SO\\_5.xsd\" namespace=\"HP.SOAQ.SampleApp/Imports\" /><xs" +
                    ":attribute name=\"fullName\" type=\"xs:string\" /><xs:attribute name=\"group\" type=\"x" +
                    "s:string\" /><xs:attribute name=\"serialize\" type=\"xs:string\" /><xs:attribute name" +
                    "=\"argType\" type=\"xs:string\" /><xs:element name=\"Envelope\" type=\"Envelope\" /><xs:" +
                    "complexType name=\"Envelope\"><xs:sequence><xs:element minOccurs=\"0\" ref=\"Header\" " +
                    "/><xs:element minOccurs=\"1\" ref=\"Body\" /></xs:sequence><xs:anyAttribute processC" +
                    "ontents=\"lax\" /></xs:complexType><xs:element name=\"Header\" type=\"Header\" /><xs:c" +
                    "omplexType name=\"Header\"><xs:sequence xmlns=\"\"><xs:any minOccurs=\"0\" maxOccurs=\"" +
                    "unbounded\" processContents=\"lax\" /></xs:sequence><xs:anyAttribute processContent" +
                    "s=\"lax\" /></xs:complexType><xs:element name=\"Body\" type=\"Body\" /><xs:complexType" +
                    " name=\"Body\"><xs:sequence xmlns=\"\"><xs:element xmlns:q1=\"HP.SOAQ.SampleApp\" ref=" +
                    "\"q1:GetFlightsResponse\" /></xs:sequence><xs:anyAttribute namespace=\"##any\" proce" +
                    "ssContents=\"lax\"><xs:annotation><xs:documentation>Prose in the spec does not spe" +
                    "cify that attributes are allowed on the Body element</xs:documentation></xs:anno" +
                    "tation></xs:anyAttribute></xs:complexType><xs:attribute name=\"mustUnderstand\"><x" +
                    "s:simpleType><xs:restriction base=\"xs:boolean\"><xs:pattern value=\"0|1\" /></xs:re" +
                    "striction></xs:simpleType></xs:attribute><xs:attribute name=\"actor\" type=\"xs:any" +
                    "URI\" /><xs:simpleType name=\"encodingStyle\"><xs:annotation><xs:documentation>\'enc" +
                    "odingStyle\' indicates any canonicalization conventions followed in the contents " +
                    "of the containing element.  For example, the value \'http://schemas.xmlsoap.org/s" +
                    "oap/encoding/\' indicates the pattern described in SOAP specification</xs:documen" +
                    "tation></xs:annotation><xs:list itemType=\"xs:anyURI\" /></xs:simpleType><xs:attri" +
                    "bute name=\"encodingStyle\" type=\"encodingStyle\" /><xs:attributeGroup name=\"encodi" +
                    "ngStyle\"><xs:attribute ref=\"encodingStyle\" /></xs:attributeGroup><xs:element nam" +
                    "e=\"Fault\" type=\"Fault\" /><xs:complexType name=\"Fault\" final=\"extension\"><xs:anno" +
                    "tation><xs:documentation>Fault reporting structure</xs:documentation></xs:annota" +
                    "tion><xs:sequence><xs:element name=\"faultcode\" type=\"xs:QName\" /><xs:element nam" +
                    "e=\"faultstring\" type=\"xs:string\" /><xs:element minOccurs=\"0\" name=\"faultactor\" t" +
                    "ype=\"xs:anyURI\" /><xs:element minOccurs=\"0\" name=\"detail\" type=\"detail\" /></xs:s" +
                    "equence></xs:complexType><xs:complexType name=\"detail\"><xs:sequence><xs:any minO" +
                    "ccurs=\"0\" maxOccurs=\"unbounded\" namespace=\"##any\" processContents=\"lax\" /></xs:s" +
                    "equence><xs:anyAttribute namespace=\"##any\" processContents=\"lax\" /></xs:complexT" +
                    "ype></xs:schema>", XmlTypeCode.None);
            stracturalPropsInfo.Add(stracturalOutputEnvelope);
            BaseCPRule StracturalRule = new StracturalRule(activity, ExpectedSchema, stracturalPropsInfo);
            activity.AddCheckpointRule(StracturalRule);

            // Checkpoint 2
            IVTDGetter actualValueGetter2 = new VTDXPathGetter(new VTDPropertyInfoBase("OutputEnvelope", "count(/*[local-name(.)='Envelope'][1]/*[local-name(.)='Header'][1]/*)"), XmlTypeCode.None, false);
            IVTDSetter actualValueSetter2 = new VTDCheckpointSetter(XmlTypeCode.Double);
            BindDirection actualBindDirection2 = new BindDirection(_flow.StServiceCallActivity4, actualValueGetter2, actualValueSetter2);
            CpValObj valueActualObject2 = new CpValObj(actualBindDirection2, XmlTypeCode.Double, false);
            CpValObj valueExpectedObject2 = new CpValObj("0", XmlTypeCode.Double);
            ValueCPRule cpRule2 = new ValueCPRule(valueActualObject2, valueExpectedObject2, PrimitiveTypeCP.EqualTo, "=", false);
            activity.AddCheckpointRule(cpRule2);

            // Checkpoint 3
            IVTDGetter actualValueGetter3 = new VTDXPathGetter(new VTDPropertyInfoBase("OutputEnvelope", "count(/*[local-name(.)='Envelope'][1]/*[local-name(.)='Body'][1]/*[local-name(.)='GetFlightsResponse'][1]/*[local-name(.)='GetFlightsResult'][1]/*[local-name(.)='Flight'])"), XmlTypeCode.None, false);
            IVTDSetter actualValueSetter3 = new VTDCheckpointSetter(XmlTypeCode.Double);
            BindDirection actualBindDirection3 = new BindDirection(_flow.StServiceCallActivity4, actualValueGetter3, actualValueSetter3);
            CpValObj valueActualObject3 = new CpValObj(actualBindDirection3, XmlTypeCode.Double, false);
            CpValObj valueExpectedObject3 = new CpValObj("9", XmlTypeCode.Double);
            ValueCPRule cpRule3 = new ValueCPRule(valueActualObject3, valueExpectedObject3, PrimitiveTypeCP.EqualTo, "=", false);
            activity.AddCheckpointRule(cpRule3);

            // Checkpoint 4
            IVTDGetter actualValueGetter4 = new VTDXPathGetter(new VTDPropertyInfoBase("OutputEnvelope", "/*[local-name(.)='Envelope'][1]/*[local-name(.)='Body'][1]/*[local-name(.)='GetFlightsResponse'][1]/*[local-name(.)='GetFlightsResult'][1]/*[local-name(.)='Flight'][1]/*[local-name(.)='Airline'][1]"), XmlTypeCode.String, false);
            IVTDSetter actualValueSetter4 = new VTDCheckpointSetter(XmlTypeCode.String);
            BindDirection actualBindDirection4 = new BindDirection(_flow.StServiceCallActivity4, actualValueGetter4, actualValueSetter4);
            CpValObj valueActualObject4 = new CpValObj(actualBindDirection4, XmlTypeCode.String, false);
            CpValObj valueExpectedObject4 = new CpValObj("NW", XmlTypeCode.String);
            ValueCPRule cpRule4 = new ValueCPRule(valueActualObject4, valueExpectedObject4, StringCP.EqualTo, "=", false);

            // Checkpoint 5
            IVTDGetter actualValueGetter5 = new VTDXPathGetter(new VTDPropertyInfoBase("OutputEnvelope", "/*[local-name(.)='Envelope'][1]/*[local-name(.)='Body'][1]/*[local-name(.)='GetFlightsResponse'][1]/*[local-name(.)='GetFlightsResult'][1]/*[local-name(.)='Flight'][1]/*[local-name(.)='ArrivalCity'][1]"), XmlTypeCode.String, false);
            IVTDSetter actualValueSetter5 = new VTDCheckpointSetter(XmlTypeCode.String);
            BindDirection actualBindDirection5 = new BindDirection(_flow.StServiceCallActivity4, actualValueGetter5, actualValueSetter5);
            CpValObj valueActualObject5 = new CpValObj(actualBindDirection5, XmlTypeCode.String, false);
            CpValObj valueExpectedObject5 = new CpValObj("Frankfurt", XmlTypeCode.String);
            ValueCPRule cpRule5 = new ValueCPRule(valueActualObject5, valueExpectedObject5, StringCP.EqualTo, "=", false);

            // Checkpoint 6
            IVTDGetter actualValueGetter6 = new VTDXPathGetter(new VTDPropertyInfoBase("OutputEnvelope", "/*[local-name(.)='Envelope'][1]/*[local-name(.)='Body'][1]/*[local-name(.)='GetFlightsResponse'][1]/*[local-name(.)='GetFlightsResult'][1]/*[local-name(.)='Flight'][1]/*[local-name(.)='ArrivalTime'][1]"), XmlTypeCode.String, false);
            IVTDSetter actualValueSetter6 = new VTDCheckpointSetter(XmlTypeCode.String);
            BindDirection actualBindDirection6 = new BindDirection(_flow.StServiceCallActivity4, actualValueGetter6, actualValueSetter6);
            CpValObj valueActualObject6 = new CpValObj(actualBindDirection6, XmlTypeCode.String, false);
            CpValObj valueExpectedObject6 = new CpValObj("07:41 PM", XmlTypeCode.String);
            ValueCPRule cpRule6 = new ValueCPRule(valueActualObject6, valueExpectedObject6, StringCP.EqualTo, "=", false);

            // Checkpoint 7
            IVTDGetter actualValueGetter7 = new VTDXPathGetter(new VTDPropertyInfoBase("OutputEnvelope", "/*[local-name(.)='Envelope'][1]/*[local-name(.)='Body'][1]/*[local-name(.)='GetFlightsResponse'][1]/*[local-name(.)='GetFlightsResult'][1]/*[local-name(.)='Flight'][1]/*[local-name(.)='DepartureCity'][1]"), XmlTypeCode.String, false);
            IVTDSetter actualValueSetter7 = new VTDCheckpointSetter(XmlTypeCode.String);
            BindDirection actualBindDirection7 = new BindDirection(_flow.StServiceCallActivity4, actualValueGetter7, actualValueSetter7);
            CpValObj valueActualObject7 = new CpValObj(actualBindDirection7, XmlTypeCode.String, false);
            CpValObj valueExpectedObject7 = new CpValObj("Denver", XmlTypeCode.String);
            ValueCPRule cpRule7 = new ValueCPRule(valueActualObject7, valueExpectedObject7, StringCP.EqualTo, "=", false);

            // Checkpoint 8
            IVTDGetter actualValueGetter8 = new VTDXPathGetter(new VTDPropertyInfoBase("OutputEnvelope", "/*[local-name(.)='Envelope'][1]/*[local-name(.)='Body'][1]/*[local-name(.)='GetFlightsResponse'][1]/*[local-name(.)='GetFlightsResult'][1]/*[local-name(.)='Flight'][1]/*[local-name(.)='DepartureTime'][1]"), XmlTypeCode.String, false);
            IVTDSetter actualValueSetter8 = new VTDCheckpointSetter(XmlTypeCode.String);
            BindDirection actualBindDirection8 = new BindDirection(_flow.StServiceCallActivity4, actualValueGetter8, actualValueSetter8);
            CpValObj valueActualObject8 = new CpValObj(actualBindDirection8, XmlTypeCode.String, false);
            CpValObj valueExpectedObject8 = new CpValObj("06:57 PM", XmlTypeCode.String);
            ValueCPRule cpRule8 = new ValueCPRule(valueActualObject8, valueExpectedObject8, StringCP.EqualTo, "=", false);

            // Checkpoint 9
            IVTDGetter actualValueGetter9 = new VTDXPathGetter(new VTDPropertyInfoBase("OutputEnvelope", "/*[local-name(.)='Envelope'][1]/*[local-name(.)='Body'][1]/*[local-name(.)='GetFlightsResponse'][1]/*[local-name(.)='GetFlightsResult'][1]/*[local-name(.)='Flight'][1]/*[local-name(.)='FlightNumber'][1]"), XmlTypeCode.Int, false);
            IVTDSetter actualValueSetter9 = new VTDCheckpointSetter(XmlTypeCode.Int);
            BindDirection actualBindDirection9 = new BindDirection(_flow.StServiceCallActivity4, actualValueGetter9, actualValueSetter9);
            CpValObj valueActualObject9 = new CpValObj(actualBindDirection9, XmlTypeCode.Int, false);
            CpValObj valueExpectedObject9 = new CpValObj("14303", XmlTypeCode.Int);
            ValueCPRule cpRule9 = new ValueCPRule(valueActualObject9, valueExpectedObject9, PrimitiveTypeCP.EqualTo, "=", false);

            // Checkpoint 10
            IVTDGetter actualValueGetter10 = new VTDXPathGetter(new VTDPropertyInfoBase("OutputEnvelope", "/*[local-name(.)='Envelope'][1]/*[local-name(.)='Body'][1]/*[local-name(.)='GetFlightsResponse'][1]/*[local-name(.)='GetFlightsResult'][1]/*[local-name(.)='Flight'][1]/*[local-name(.)='Price'][1]"), XmlTypeCode.Float, false);
            IVTDSetter actualValueSetter10 = new VTDCheckpointSetter(XmlTypeCode.Float);
            BindDirection actualBindDirection10 = new BindDirection(_flow.StServiceCallActivity4, actualValueGetter10, actualValueSetter10);
            CpValObj valueActualObject10 = new CpValObj(actualBindDirection10, XmlTypeCode.Float, false);
            CpValObj valueExpectedObject10 = new CpValObj("100.8", XmlTypeCode.Float);
            ValueCPRule cpRule10 = new ValueCPRule(valueActualObject10, valueExpectedObject10, PrimitiveTypeCP.EqualTo, "=", false);

            // Checkpoint 11
            IVTDGetter actualValueGetter11 = new VTDXPathGetter(new VTDPropertyInfoBase("OutputEnvelope", "/*[local-name(.)='Envelope'][1]/*[local-name(.)='Body'][1]/*[local-name(.)='GetFlightsResponse'][1]/*[local-name(.)='GetFlightsResult'][1]/*[local-name(.)='Flight'][2]/*[local-name(.)='Airline'][1]"), XmlTypeCode.String, false);
            IVTDSetter actualValueSetter11 = new VTDCheckpointSetter(XmlTypeCode.String);
            BindDirection actualBindDirection11 = new BindDirection(_flow.StServiceCallActivity4, actualValueGetter11, actualValueSetter11);
            CpValObj valueActualObject11 = new CpValObj(actualBindDirection11, XmlTypeCode.String, false);
            CpValObj valueExpectedObject11 = new CpValObj("NW", XmlTypeCode.String);
            ValueCPRule cpRule11 = new ValueCPRule(valueActualObject11, valueExpectedObject11, StringCP.EqualTo, "=", false);

            // Checkpoint 12
            IVTDGetter actualValueGetter12 = new VTDXPathGetter(new VTDPropertyInfoBase("OutputEnvelope", "/*[local-name(.)='Envelope'][1]/*[local-name(.)='Body'][1]/*[local-name(.)='GetFlightsResponse'][1]/*[local-name(.)='GetFlightsResult'][1]/*[local-name(.)='Flight'][2]/*[local-name(.)='ArrivalCity'][1]"), XmlTypeCode.String, false);
            IVTDSetter actualValueSetter12 = new VTDCheckpointSetter(XmlTypeCode.String);
            BindDirection actualBindDirection12 = new BindDirection(_flow.StServiceCallActivity4, actualValueGetter12, actualValueSetter12);
            CpValObj valueActualObject12 = new CpValObj(actualBindDirection12, XmlTypeCode.String, false);
            CpValObj valueExpectedObject12 = new CpValObj("Frankfurt", XmlTypeCode.String);
            ValueCPRule cpRule12 = new ValueCPRule(valueActualObject12, valueExpectedObject12, StringCP.EqualTo, "=", false);

            // Checkpoint 13
            IVTDGetter actualValueGetter13 = new VTDXPathGetter(new VTDPropertyInfoBase("OutputEnvelope", "/*[local-name(.)='Envelope'][1]/*[local-name(.)='Body'][1]/*[local-name(.)='GetFlightsResponse'][1]/*[local-name(.)='GetFlightsResult'][1]/*[local-name(.)='Flight'][2]/*[local-name(.)='ArrivalTime'][1]"), XmlTypeCode.String, false);
            IVTDSetter actualValueSetter13 = new VTDCheckpointSetter(XmlTypeCode.String);
            BindDirection actualBindDirection13 = new BindDirection(_flow.StServiceCallActivity4, actualValueGetter13, actualValueSetter13);
            CpValObj valueActualObject13 = new CpValObj(actualBindDirection13, XmlTypeCode.String, false);
            CpValObj valueExpectedObject13 = new CpValObj("06:29 PM", XmlTypeCode.String);
            ValueCPRule cpRule13 = new ValueCPRule(valueActualObject13, valueExpectedObject13, StringCP.EqualTo, "=", false);

            // Checkpoint 14
            IVTDGetter actualValueGetter14 = new VTDXPathGetter(new VTDPropertyInfoBase("OutputEnvelope", "/*[local-name(.)='Envelope'][1]/*[local-name(.)='Body'][1]/*[local-name(.)='GetFlightsResponse'][1]/*[local-name(.)='GetFlightsResult'][1]/*[local-name(.)='Flight'][2]/*[local-name(.)='DepartureCity'][1]"), XmlTypeCode.String, false);
            IVTDSetter actualValueSetter14 = new VTDCheckpointSetter(XmlTypeCode.String);
            BindDirection actualBindDirection14 = new BindDirection(_flow.StServiceCallActivity4, actualValueGetter14, actualValueSetter14);
            CpValObj valueActualObject14 = new CpValObj(actualBindDirection14, XmlTypeCode.String, false);
            CpValObj valueExpectedObject14 = new CpValObj("Denver", XmlTypeCode.String);
            ValueCPRule cpRule14 = new ValueCPRule(valueActualObject14, valueExpectedObject14, StringCP.EqualTo, "=", false);

            // Checkpoint 15
            IVTDGetter actualValueGetter15 = new VTDXPathGetter(new VTDPropertyInfoBase("OutputEnvelope", "/*[local-name(.)='Envelope'][1]/*[local-name(.)='Body'][1]/*[local-name(.)='GetFlightsResponse'][1]/*[local-name(.)='GetFlightsResult'][1]/*[local-name(.)='Flight'][2]/*[local-name(.)='DepartureTime'][1]"), XmlTypeCode.String, false);
            IVTDSetter actualValueSetter15 = new VTDCheckpointSetter(XmlTypeCode.String);
            BindDirection actualBindDirection15 = new BindDirection(_flow.StServiceCallActivity4, actualValueGetter15, actualValueSetter15);
            CpValObj valueActualObject15 = new CpValObj(actualBindDirection15, XmlTypeCode.String, false);
            CpValObj valueExpectedObject15 = new CpValObj("05:45 PM", XmlTypeCode.String);
            ValueCPRule cpRule15 = new ValueCPRule(valueActualObject15, valueExpectedObject15, StringCP.EqualTo, "=", false);

            // Checkpoint 16
            IVTDGetter actualValueGetter16 = new VTDXPathGetter(new VTDPropertyInfoBase("OutputEnvelope", "/*[local-name(.)='Envelope'][1]/*[local-name(.)='Body'][1]/*[local-name(.)='GetFlightsResponse'][1]/*[local-name(.)='GetFlightsResult'][1]/*[local-name(.)='Flight'][2]/*[local-name(.)='FlightNumber'][1]"), XmlTypeCode.Int, false);
            IVTDSetter actualValueSetter16 = new VTDCheckpointSetter(XmlTypeCode.Int);
            BindDirection actualBindDirection16 = new BindDirection(_flow.StServiceCallActivity4, actualValueGetter16, actualValueSetter16);
            CpValObj valueActualObject16 = new CpValObj(actualBindDirection16, XmlTypeCode.Int, false);
            CpValObj valueExpectedObject16 = new CpValObj("14438", XmlTypeCode.Int);
            ValueCPRule cpRule16 = new ValueCPRule(valueActualObject16, valueExpectedObject16, PrimitiveTypeCP.EqualTo, "=", false);

            // Checkpoint 17
            IVTDGetter actualValueGetter17 = new VTDXPathGetter(new VTDPropertyInfoBase("OutputEnvelope", "/*[local-name(.)='Envelope'][1]/*[local-name(.)='Body'][1]/*[local-name(.)='GetFlightsResponse'][1]/*[local-name(.)='GetFlightsResult'][1]/*[local-name(.)='Flight'][2]/*[local-name(.)='Price'][1]"), XmlTypeCode.Float, false);
            IVTDSetter actualValueSetter17 = new VTDCheckpointSetter(XmlTypeCode.Float);
            BindDirection actualBindDirection17 = new BindDirection(_flow.StServiceCallActivity4, actualValueGetter17, actualValueSetter17);
            CpValObj valueActualObject17 = new CpValObj(actualBindDirection17, XmlTypeCode.Float, false);
            CpValObj valueExpectedObject17 = new CpValObj("110", XmlTypeCode.Float);
            ValueCPRule cpRule17 = new ValueCPRule(valueActualObject17, valueExpectedObject17, PrimitiveTypeCP.EqualTo, "=", false);

            // Checkpoint 18
            IVTDGetter actualValueGetter18 = new VTDXPathGetter(new VTDPropertyInfoBase("OutputEnvelope", "/*[local-name(.)='Envelope'][1]/*[local-name(.)='Body'][1]/*[local-name(.)='GetFlightsResponse'][1]/*[local-name(.)='GetFlightsResult'][1]/*[local-name(.)='Flight'][3]/*[local-name(.)='Airline'][1]"), XmlTypeCode.String, false);
            IVTDSetter actualValueSetter18 = new VTDCheckpointSetter(XmlTypeCode.String);
            BindDirection actualBindDirection18 = new BindDirection(_flow.StServiceCallActivity4, actualValueGetter18, actualValueSetter18);
            CpValObj valueActualObject18 = new CpValObj(actualBindDirection18, XmlTypeCode.String, false);
            CpValObj valueExpectedObject18 = new CpValObj("AA", XmlTypeCode.String);
            ValueCPRule cpRule18 = new ValueCPRule(valueActualObject18, valueExpectedObject18, StringCP.EqualTo, "=", false);

            // Checkpoint 19
            IVTDGetter actualValueGetter19 = new VTDXPathGetter(new VTDPropertyInfoBase("OutputEnvelope", "/*[local-name(.)='Envelope'][1]/*[local-name(.)='Body'][1]/*[local-name(.)='GetFlightsResponse'][1]/*[local-name(.)='GetFlightsResult'][1]/*[local-name(.)='Flight'][3]/*[local-name(.)='ArrivalCity'][1]"), XmlTypeCode.String, false);
            IVTDSetter actualValueSetter19 = new VTDCheckpointSetter(XmlTypeCode.String);
            BindDirection actualBindDirection19 = new BindDirection(_flow.StServiceCallActivity4, actualValueGetter19, actualValueSetter19);
            CpValObj valueActualObject19 = new CpValObj(actualBindDirection19, XmlTypeCode.String, false);
            CpValObj valueExpectedObject19 = new CpValObj("Frankfurt", XmlTypeCode.String);
            ValueCPRule cpRule19 = new ValueCPRule(valueActualObject19, valueExpectedObject19, StringCP.EqualTo, "=", false);

            // Checkpoint 20
            IVTDGetter actualValueGetter20 = new VTDXPathGetter(new VTDPropertyInfoBase("OutputEnvelope", "/*[local-name(.)='Envelope'][1]/*[local-name(.)='Body'][1]/*[local-name(.)='GetFlightsResponse'][1]/*[local-name(.)='GetFlightsResult'][1]/*[local-name(.)='Flight'][3]/*[local-name(.)='ArrivalTime'][1]"), XmlTypeCode.String, false);
            IVTDSetter actualValueSetter20 = new VTDCheckpointSetter(XmlTypeCode.String);
            BindDirection actualBindDirection20 = new BindDirection(_flow.StServiceCallActivity4, actualValueGetter20, actualValueSetter20);
            CpValObj valueActualObject20 = new CpValObj(actualBindDirection20, XmlTypeCode.String, false);
            CpValObj valueExpectedObject20 = new CpValObj("08:45 AM", XmlTypeCode.String);
            ValueCPRule cpRule20 = new ValueCPRule(valueActualObject20, valueExpectedObject20, StringCP.EqualTo, "=", false);

            // Checkpoint 21
            IVTDGetter actualValueGetter21 = new VTDXPathGetter(new VTDPropertyInfoBase("OutputEnvelope", "/*[local-name(.)='Envelope'][1]/*[local-name(.)='Body'][1]/*[local-name(.)='GetFlightsResponse'][1]/*[local-name(.)='GetFlightsResult'][1]/*[local-name(.)='Flight'][3]/*[local-name(.)='DepartureCity'][1]"), XmlTypeCode.String, false);
            IVTDSetter actualValueSetter21 = new VTDCheckpointSetter(XmlTypeCode.String);
            BindDirection actualBindDirection21 = new BindDirection(_flow.StServiceCallActivity4, actualValueGetter21, actualValueSetter21);
            CpValObj valueActualObject21 = new CpValObj(actualBindDirection21, XmlTypeCode.String, false);
            CpValObj valueExpectedObject21 = new CpValObj("Denver", XmlTypeCode.String);
            ValueCPRule cpRule21 = new ValueCPRule(valueActualObject21, valueExpectedObject21, StringCP.EqualTo, "=", false);

            // Checkpoint 22
            IVTDGetter actualValueGetter22 = new VTDXPathGetter(new VTDPropertyInfoBase("OutputEnvelope", "/*[local-name(.)='Envelope'][1]/*[local-name(.)='Body'][1]/*[local-name(.)='GetFlightsResponse'][1]/*[local-name(.)='GetFlightsResult'][1]/*[local-name(.)='Flight'][3]/*[local-name(.)='DepartureTime'][1]"), XmlTypeCode.String, false);
            IVTDSetter actualValueSetter22 = new VTDCheckpointSetter(XmlTypeCode.String);
            BindDirection actualBindDirection22 = new BindDirection(_flow.StServiceCallActivity4, actualValueGetter22, actualValueSetter22);
            CpValObj valueActualObject22 = new CpValObj(actualBindDirection22, XmlTypeCode.String, false);
            CpValObj valueExpectedObject22 = new CpValObj("08:00 AM", XmlTypeCode.String);
            ValueCPRule cpRule22 = new ValueCPRule(valueActualObject22, valueExpectedObject22, StringCP.EqualTo, "=", false);

            // Checkpoint 23
            IVTDGetter actualValueGetter23 = new VTDXPathGetter(new VTDPropertyInfoBase("OutputEnvelope", "/*[local-name(.)='Envelope'][1]/*[local-name(.)='Body'][1]/*[local-name(.)='GetFlightsResponse'][1]/*[local-name(.)='GetFlightsResult'][1]/*[local-name(.)='Flight'][3]/*[local-name(.)='FlightNumber'][1]"), XmlTypeCode.Int, false);
            IVTDSetter actualValueSetter23 = new VTDCheckpointSetter(XmlTypeCode.Int);
            BindDirection actualBindDirection23 = new BindDirection(_flow.StServiceCallActivity4, actualValueGetter23, actualValueSetter23);
            CpValObj valueActualObject23 = new CpValObj(actualBindDirection23, XmlTypeCode.Int, false);
            CpValObj valueExpectedObject23 = new CpValObj("15829", XmlTypeCode.Int);
            ValueCPRule cpRule23 = new ValueCPRule(valueActualObject23, valueExpectedObject23, PrimitiveTypeCP.EqualTo, "=", false);

            // Checkpoint 24
            IVTDGetter actualValueGetter24 = new VTDXPathGetter(new VTDPropertyInfoBase("OutputEnvelope", "/*[local-name(.)='Envelope'][1]/*[local-name(.)='Body'][1]/*[local-name(.)='GetFlightsResponse'][1]/*[local-name(.)='GetFlightsResult'][1]/*[local-name(.)='Flight'][3]/*[local-name(.)='Price'][1]"), XmlTypeCode.Float, false);
            IVTDSetter actualValueSetter24 = new VTDCheckpointSetter(XmlTypeCode.Float);
            BindDirection actualBindDirection24 = new BindDirection(_flow.StServiceCallActivity4, actualValueGetter24, actualValueSetter24);
            CpValObj valueActualObject24 = new CpValObj(actualBindDirection24, XmlTypeCode.Float, false);
            CpValObj valueExpectedObject24 = new CpValObj("100.5", XmlTypeCode.Float);
            ValueCPRule cpRule24 = new ValueCPRule(valueActualObject24, valueExpectedObject24, PrimitiveTypeCP.EqualTo, "=", false);

            // Checkpoint 25
            IVTDGetter actualValueGetter25 = new VTDXPathGetter(new VTDPropertyInfoBase("OutputEnvelope", "/*[local-name(.)='Envelope'][1]/*[local-name(.)='Body'][1]/*[local-name(.)='GetFlightsResponse'][1]/*[local-name(.)='GetFlightsResult'][1]/*[local-name(.)='Flight'][4]/*[local-name(.)='Airline'][1]"), XmlTypeCode.String, false);
            IVTDSetter actualValueSetter25 = new VTDCheckpointSetter(XmlTypeCode.String);
            BindDirection actualBindDirection25 = new BindDirection(_flow.StServiceCallActivity4, actualValueGetter25, actualValueSetter25);
            CpValObj valueActualObject25 = new CpValObj(actualBindDirection25, XmlTypeCode.String, false);
            CpValObj valueExpectedObject25 = new CpValObj("AA", XmlTypeCode.String);
            ValueCPRule cpRule25 = new ValueCPRule(valueActualObject25, valueExpectedObject25, StringCP.EqualTo, "=", false);

            // Checkpoint 26
            IVTDGetter actualValueGetter26 = new VTDXPathGetter(new VTDPropertyInfoBase("OutputEnvelope", "/*[local-name(.)='Envelope'][1]/*[local-name(.)='Body'][1]/*[local-name(.)='GetFlightsResponse'][1]/*[local-name(.)='GetFlightsResult'][1]/*[local-name(.)='Flight'][4]/*[local-name(.)='ArrivalCity'][1]"), XmlTypeCode.String, false);
            IVTDSetter actualValueSetter26 = new VTDCheckpointSetter(XmlTypeCode.String);
            BindDirection actualBindDirection26 = new BindDirection(_flow.StServiceCallActivity4, actualValueGetter26, actualValueSetter26);
            CpValObj valueActualObject26 = new CpValObj(actualBindDirection26, XmlTypeCode.String, false);
            CpValObj valueExpectedObject26 = new CpValObj("Frankfurt", XmlTypeCode.String);
            ValueCPRule cpRule26 = new ValueCPRule(valueActualObject26, valueExpectedObject26, StringCP.EqualTo, "=", false);

            // Checkpoint 27
            IVTDGetter actualValueGetter27 = new VTDXPathGetter(new VTDPropertyInfoBase("OutputEnvelope", "/*[local-name(.)='Envelope'][1]/*[local-name(.)='Body'][1]/*[local-name(.)='GetFlightsResponse'][1]/*[local-name(.)='GetFlightsResult'][1]/*[local-name(.)='Flight'][4]/*[local-name(.)='ArrivalTime'][1]"), XmlTypeCode.String, false);
            IVTDSetter actualValueSetter27 = new VTDCheckpointSetter(XmlTypeCode.String);
            BindDirection actualBindDirection27 = new BindDirection(_flow.StServiceCallActivity4, actualValueGetter27, actualValueSetter27);
            CpValObj valueActualObject27 = new CpValObj(actualBindDirection27, XmlTypeCode.String, false);
            CpValObj valueExpectedObject27 = new CpValObj("11:09 AM", XmlTypeCode.String);
            ValueCPRule cpRule27 = new ValueCPRule(valueActualObject27, valueExpectedObject27, StringCP.EqualTo, "=", false);

            // Checkpoint 28
            IVTDGetter actualValueGetter28 = new VTDXPathGetter(new VTDPropertyInfoBase("OutputEnvelope", "/*[local-name(.)='Envelope'][1]/*[local-name(.)='Body'][1]/*[local-name(.)='GetFlightsResponse'][1]/*[local-name(.)='GetFlightsResult'][1]/*[local-name(.)='Flight'][4]/*[local-name(.)='DepartureCity'][1]"), XmlTypeCode.String, false);
            IVTDSetter actualValueSetter28 = new VTDCheckpointSetter(XmlTypeCode.String);
            BindDirection actualBindDirection28 = new BindDirection(_flow.StServiceCallActivity4, actualValueGetter28, actualValueSetter28);
            CpValObj valueActualObject28 = new CpValObj(actualBindDirection28, XmlTypeCode.String, false);
            CpValObj valueExpectedObject28 = new CpValObj("Denver", XmlTypeCode.String);
            ValueCPRule cpRule28 = new ValueCPRule(valueActualObject28, valueExpectedObject28, StringCP.EqualTo, "=", false);

            // Checkpoint 29
            IVTDGetter actualValueGetter29 = new VTDXPathGetter(new VTDPropertyInfoBase("OutputEnvelope", "/*[local-name(.)='Envelope'][1]/*[local-name(.)='Body'][1]/*[local-name(.)='GetFlightsResponse'][1]/*[local-name(.)='GetFlightsResult'][1]/*[local-name(.)='Flight'][4]/*[local-name(.)='DepartureTime'][1]"), XmlTypeCode.String, false);
            IVTDSetter actualValueSetter29 = new VTDCheckpointSetter(XmlTypeCode.String);
            BindDirection actualBindDirection29 = new BindDirection(_flow.StServiceCallActivity4, actualValueGetter29, actualValueSetter29);
            CpValObj valueActualObject29 = new CpValObj(actualBindDirection29, XmlTypeCode.String, false);
            CpValObj valueExpectedObject29 = new CpValObj("10:24 AM", XmlTypeCode.String);
            ValueCPRule cpRule29 = new ValueCPRule(valueActualObject29, valueExpectedObject29, StringCP.EqualTo, "=", false);

            // Checkpoint 30
            IVTDGetter actualValueGetter30 = new VTDXPathGetter(new VTDPropertyInfoBase("OutputEnvelope", "/*[local-name(.)='Envelope'][1]/*[local-name(.)='Body'][1]/*[local-name(.)='GetFlightsResponse'][1]/*[local-name(.)='GetFlightsResult'][1]/*[local-name(.)='Flight'][4]/*[local-name(.)='FlightNumber'][1]"), XmlTypeCode.Int, false);
            IVTDSetter actualValueSetter30 = new VTDCheckpointSetter(XmlTypeCode.Int);
            BindDirection actualBindDirection30 = new BindDirection(_flow.StServiceCallActivity4, actualValueGetter30, actualValueSetter30);
            CpValObj valueActualObject30 = new CpValObj(actualBindDirection30, XmlTypeCode.Int, false);
            CpValObj valueExpectedObject30 = new CpValObj("15833", XmlTypeCode.Int);
            ValueCPRule cpRule30 = new ValueCPRule(valueActualObject30, valueExpectedObject30, PrimitiveTypeCP.EqualTo, "=", false);

            // Checkpoint 31
            IVTDGetter actualValueGetter31 = new VTDXPathGetter(new VTDPropertyInfoBase("OutputEnvelope", "/*[local-name(.)='Envelope'][1]/*[local-name(.)='Body'][1]/*[local-name(.)='GetFlightsResponse'][1]/*[local-name(.)='GetFlightsResult'][1]/*[local-name(.)='Flight'][4]/*[local-name(.)='Price'][1]"), XmlTypeCode.Float, false);
            IVTDSetter actualValueSetter31 = new VTDCheckpointSetter(XmlTypeCode.Float);
            BindDirection actualBindDirection31 = new BindDirection(_flow.StServiceCallActivity4, actualValueGetter31, actualValueSetter31);
            CpValObj valueActualObject31 = new CpValObj(actualBindDirection31, XmlTypeCode.Float, false);
            CpValObj valueExpectedObject31 = new CpValObj("103.4", XmlTypeCode.Float);
            ValueCPRule cpRule31 = new ValueCPRule(valueActualObject31, valueExpectedObject31, PrimitiveTypeCP.EqualTo, "=", false);

            // Checkpoint 32
            IVTDGetter actualValueGetter32 = new VTDXPathGetter(new VTDPropertyInfoBase("OutputEnvelope", "/*[local-name(.)='Envelope'][1]/*[local-name(.)='Body'][1]/*[local-name(.)='GetFlightsResponse'][1]/*[local-name(.)='GetFlightsResult'][1]/*[local-name(.)='Flight'][5]/*[local-name(.)='Airline'][1]"), XmlTypeCode.String, false);
            IVTDSetter actualValueSetter32 = new VTDCheckpointSetter(XmlTypeCode.String);
            BindDirection actualBindDirection32 = new BindDirection(_flow.StServiceCallActivity4, actualValueGetter32, actualValueSetter32);
            CpValObj valueActualObject32 = new CpValObj(actualBindDirection32, XmlTypeCode.String, false);
            CpValObj valueExpectedObject32 = new CpValObj("AA", XmlTypeCode.String);
            ValueCPRule cpRule32 = new ValueCPRule(valueActualObject32, valueExpectedObject32, StringCP.EqualTo, "=", false);

            // Checkpoint 33
            IVTDGetter actualValueGetter33 = new VTDXPathGetter(new VTDPropertyInfoBase("OutputEnvelope", "/*[local-name(.)='Envelope'][1]/*[local-name(.)='Body'][1]/*[local-name(.)='GetFlightsResponse'][1]/*[local-name(.)='GetFlightsResult'][1]/*[local-name(.)='Flight'][5]/*[local-name(.)='ArrivalCity'][1]"), XmlTypeCode.String, false);
            IVTDSetter actualValueSetter33 = new VTDCheckpointSetter(XmlTypeCode.String);
            BindDirection actualBindDirection33 = new BindDirection(_flow.StServiceCallActivity4, actualValueGetter33, actualValueSetter33);
            CpValObj valueActualObject33 = new CpValObj(actualBindDirection33, XmlTypeCode.String, false);
            CpValObj valueExpectedObject33 = new CpValObj("Frankfurt", XmlTypeCode.String);
            ValueCPRule cpRule33 = new ValueCPRule(valueActualObject33, valueExpectedObject33, StringCP.EqualTo, "=", false);

            // Checkpoint 34
            IVTDGetter actualValueGetter34 = new VTDXPathGetter(new VTDPropertyInfoBase("OutputEnvelope", "/*[local-name(.)='Envelope'][1]/*[local-name(.)='Body'][1]/*[local-name(.)='GetFlightsResponse'][1]/*[local-name(.)='GetFlightsResult'][1]/*[local-name(.)='Flight'][5]/*[local-name(.)='ArrivalTime'][1]"), XmlTypeCode.String, false);
            IVTDSetter actualValueSetter34 = new VTDCheckpointSetter(XmlTypeCode.String);
            BindDirection actualBindDirection34 = new BindDirection(_flow.StServiceCallActivity4, actualValueGetter34, actualValueSetter34);
            CpValObj valueActualObject34 = new CpValObj(actualBindDirection34, XmlTypeCode.String, false);
            CpValObj valueExpectedObject34 = new CpValObj("01:33 PM", XmlTypeCode.String);
            ValueCPRule cpRule34 = new ValueCPRule(valueActualObject34, valueExpectedObject34, StringCP.EqualTo, "=", false);

            // Checkpoint 35
            IVTDGetter actualValueGetter35 = new VTDXPathGetter(new VTDPropertyInfoBase("OutputEnvelope", "/*[local-name(.)='Envelope'][1]/*[local-name(.)='Body'][1]/*[local-name(.)='GetFlightsResponse'][1]/*[local-name(.)='GetFlightsResult'][1]/*[local-name(.)='Flight'][5]/*[local-name(.)='DepartureCity'][1]"), XmlTypeCode.String, false);
            IVTDSetter actualValueSetter35 = new VTDCheckpointSetter(XmlTypeCode.String);
            BindDirection actualBindDirection35 = new BindDirection(_flow.StServiceCallActivity4, actualValueGetter35, actualValueSetter35);
            CpValObj valueActualObject35 = new CpValObj(actualBindDirection35, XmlTypeCode.String, false);
            CpValObj valueExpectedObject35 = new CpValObj("Denver", XmlTypeCode.String);
            ValueCPRule cpRule35 = new ValueCPRule(valueActualObject35, valueExpectedObject35, StringCP.EqualTo, "=", false);

            // Checkpoint 36
            IVTDGetter actualValueGetter36 = new VTDXPathGetter(new VTDPropertyInfoBase("OutputEnvelope", "/*[local-name(.)='Envelope'][1]/*[local-name(.)='Body'][1]/*[local-name(.)='GetFlightsResponse'][1]/*[local-name(.)='GetFlightsResult'][1]/*[local-name(.)='Flight'][5]/*[local-name(.)='DepartureTime'][1]"), XmlTypeCode.String, false);
            IVTDSetter actualValueSetter36 = new VTDCheckpointSetter(XmlTypeCode.String);
            BindDirection actualBindDirection36 = new BindDirection(_flow.StServiceCallActivity4, actualValueGetter36, actualValueSetter36);
            CpValObj valueActualObject36 = new CpValObj(actualBindDirection36, XmlTypeCode.String, false);
            CpValObj valueExpectedObject36 = new CpValObj("12:48 PM", XmlTypeCode.String);
            ValueCPRule cpRule36 = new ValueCPRule(valueActualObject36, valueExpectedObject36, StringCP.EqualTo, "=", false);

            // Checkpoint 37
            IVTDGetter actualValueGetter37 = new VTDXPathGetter(new VTDPropertyInfoBase("OutputEnvelope", "/*[local-name(.)='Envelope'][1]/*[local-name(.)='Body'][1]/*[local-name(.)='GetFlightsResponse'][1]/*[local-name(.)='GetFlightsResult'][1]/*[local-name(.)='Flight'][5]/*[local-name(.)='FlightNumber'][1]"), XmlTypeCode.Int, false);
            IVTDSetter actualValueSetter37 = new VTDCheckpointSetter(XmlTypeCode.Int);
            BindDirection actualBindDirection37 = new BindDirection(_flow.StServiceCallActivity4, actualValueGetter37, actualValueSetter37);
            CpValObj valueActualObject37 = new CpValObj(actualBindDirection37, XmlTypeCode.Int, false);
            CpValObj valueExpectedObject37 = new CpValObj("15837", XmlTypeCode.Int);
            ValueCPRule cpRule37 = new ValueCPRule(valueActualObject37, valueExpectedObject37, PrimitiveTypeCP.EqualTo, "=", false);

            // Checkpoint 38
            IVTDGetter actualValueGetter38 = new VTDXPathGetter(new VTDPropertyInfoBase("OutputEnvelope", "/*[local-name(.)='Envelope'][1]/*[local-name(.)='Body'][1]/*[local-name(.)='GetFlightsResponse'][1]/*[local-name(.)='GetFlightsResult'][1]/*[local-name(.)='Flight'][5]/*[local-name(.)='Price'][1]"), XmlTypeCode.Float, false);
            IVTDSetter actualValueSetter38 = new VTDCheckpointSetter(XmlTypeCode.Float);
            BindDirection actualBindDirection38 = new BindDirection(_flow.StServiceCallActivity4, actualValueGetter38, actualValueSetter38);
            CpValObj valueActualObject38 = new CpValObj(actualBindDirection38, XmlTypeCode.Float, false);
            CpValObj valueExpectedObject38 = new CpValObj("108", XmlTypeCode.Float);
            ValueCPRule cpRule38 = new ValueCPRule(valueActualObject38, valueExpectedObject38, PrimitiveTypeCP.EqualTo, "=", false);

            // Checkpoint 39
            IVTDGetter actualValueGetter39 = new VTDXPathGetter(new VTDPropertyInfoBase("OutputEnvelope", "/*[local-name(.)='Envelope'][1]/*[local-name(.)='Body'][1]/*[local-name(.)='GetFlightsResponse'][1]/*[local-name(.)='GetFlightsResult'][1]/*[local-name(.)='Flight'][6]/*[local-name(.)='Airline'][1]"), XmlTypeCode.String, false);
            IVTDSetter actualValueSetter39 = new VTDCheckpointSetter(XmlTypeCode.String);
            BindDirection actualBindDirection39 = new BindDirection(_flow.StServiceCallActivity4, actualValueGetter39, actualValueSetter39);
            CpValObj valueActualObject39 = new CpValObj(actualBindDirection39, XmlTypeCode.String, false);
            CpValObj valueExpectedObject39 = new CpValObj("DL", XmlTypeCode.String);
            ValueCPRule cpRule39 = new ValueCPRule(valueActualObject39, valueExpectedObject39, StringCP.EqualTo, "=", false);

            // Checkpoint 40
            IVTDGetter actualValueGetter40 = new VTDXPathGetter(new VTDPropertyInfoBase("OutputEnvelope", "/*[local-name(.)='Envelope'][1]/*[local-name(.)='Body'][1]/*[local-name(.)='GetFlightsResponse'][1]/*[local-name(.)='GetFlightsResult'][1]/*[local-name(.)='Flight'][6]/*[local-name(.)='ArrivalCity'][1]"), XmlTypeCode.String, false);
            IVTDSetter actualValueSetter40 = new VTDCheckpointSetter(XmlTypeCode.String);
            BindDirection actualBindDirection40 = new BindDirection(_flow.StServiceCallActivity4, actualValueGetter40, actualValueSetter40);
            CpValObj valueActualObject40 = new CpValObj(actualBindDirection40, XmlTypeCode.String, false);
            CpValObj valueExpectedObject40 = new CpValObj("Frankfurt", XmlTypeCode.String);
            ValueCPRule cpRule40 = new ValueCPRule(valueActualObject40, valueExpectedObject40, StringCP.EqualTo, "=", false);

            // Checkpoint 41
            IVTDGetter actualValueGetter41 = new VTDXPathGetter(new VTDPropertyInfoBase("OutputEnvelope", "/*[local-name(.)='Envelope'][1]/*[local-name(.)='Body'][1]/*[local-name(.)='GetFlightsResponse'][1]/*[local-name(.)='GetFlightsResult'][1]/*[local-name(.)='Flight'][6]/*[local-name(.)='ArrivalTime'][1]"), XmlTypeCode.String, false);
            IVTDSetter actualValueSetter41 = new VTDCheckpointSetter(XmlTypeCode.String);
            BindDirection actualBindDirection41 = new BindDirection(_flow.StServiceCallActivity4, actualValueGetter41, actualValueSetter41);
            CpValObj valueActualObject41 = new CpValObj(actualBindDirection41, XmlTypeCode.String, false);
            CpValObj valueExpectedObject41 = new CpValObj("04:42 PM", XmlTypeCode.String);
            ValueCPRule cpRule41 = new ValueCPRule(valueActualObject41, valueExpectedObject41, StringCP.EqualTo, "=", false);

            // Checkpoint 42
            IVTDGetter actualValueGetter42 = new VTDXPathGetter(new VTDPropertyInfoBase("OutputEnvelope", "/*[local-name(.)='Envelope'][1]/*[local-name(.)='Body'][1]/*[local-name(.)='GetFlightsResponse'][1]/*[local-name(.)='GetFlightsResult'][1]/*[local-name(.)='Flight'][6]/*[local-name(.)='DepartureCity'][1]"), XmlTypeCode.String, false);
            IVTDSetter actualValueSetter42 = new VTDCheckpointSetter(XmlTypeCode.String);
            BindDirection actualBindDirection42 = new BindDirection(_flow.StServiceCallActivity4, actualValueGetter42, actualValueSetter42);
            CpValObj valueActualObject42 = new CpValObj(actualBindDirection42, XmlTypeCode.String, false);
            CpValObj valueExpectedObject42 = new CpValObj("Denver", XmlTypeCode.String);
            ValueCPRule cpRule42 = new ValueCPRule(valueActualObject42, valueExpectedObject42, StringCP.EqualTo, "=", false);

            // Checkpoint 43
            IVTDGetter actualValueGetter43 = new VTDXPathGetter(new VTDPropertyInfoBase("OutputEnvelope", "/*[local-name(.)='Envelope'][1]/*[local-name(.)='Body'][1]/*[local-name(.)='GetFlightsResponse'][1]/*[local-name(.)='GetFlightsResult'][1]/*[local-name(.)='Flight'][6]/*[local-name(.)='DepartureTime'][1]"), XmlTypeCode.String, false);
            IVTDSetter actualValueSetter43 = new VTDCheckpointSetter(XmlTypeCode.String);
            BindDirection actualBindDirection43 = new BindDirection(_flow.StServiceCallActivity4, actualValueGetter43, actualValueSetter43);
            CpValObj valueActualObject43 = new CpValObj(actualBindDirection43, XmlTypeCode.String, false);
            CpValObj valueExpectedObject43 = new CpValObj("03:12 PM", XmlTypeCode.String);
            ValueCPRule cpRule43 = new ValueCPRule(valueActualObject43, valueExpectedObject43, StringCP.EqualTo, "=", false);

            // Checkpoint 44
            IVTDGetter actualValueGetter44 = new VTDXPathGetter(new VTDPropertyInfoBase("OutputEnvelope", "/*[local-name(.)='Envelope'][1]/*[local-name(.)='Body'][1]/*[local-name(.)='GetFlightsResponse'][1]/*[local-name(.)='GetFlightsResult'][1]/*[local-name(.)='Flight'][6]/*[local-name(.)='FlightNumber'][1]"), XmlTypeCode.Int, false);
            IVTDSetter actualValueSetter44 = new VTDCheckpointSetter(XmlTypeCode.Int);
            BindDirection actualBindDirection44 = new BindDirection(_flow.StServiceCallActivity4, actualValueGetter44, actualValueSetter44);
            CpValObj valueActualObject44 = new CpValObj(actualBindDirection44, XmlTypeCode.Int, false);
            CpValObj valueExpectedObject44 = new CpValObj("15840", XmlTypeCode.Int);
            ValueCPRule cpRule44 = new ValueCPRule(valueActualObject44, valueExpectedObject44, PrimitiveTypeCP.EqualTo, "=", false);

            // Checkpoint 45
            IVTDGetter actualValueGetter45 = new VTDXPathGetter(new VTDPropertyInfoBase("OutputEnvelope", "/*[local-name(.)='Envelope'][1]/*[local-name(.)='Body'][1]/*[local-name(.)='GetFlightsResponse'][1]/*[local-name(.)='GetFlightsResult'][1]/*[local-name(.)='Flight'][6]/*[local-name(.)='Price'][1]"), XmlTypeCode.Float, false);
            IVTDSetter actualValueSetter45 = new VTDCheckpointSetter(XmlTypeCode.Float);
            BindDirection actualBindDirection45 = new BindDirection(_flow.StServiceCallActivity4, actualValueGetter45, actualValueSetter45);
            CpValObj valueActualObject45 = new CpValObj(actualBindDirection45, XmlTypeCode.Float, false);
            CpValObj valueExpectedObject45 = new CpValObj("173.47", XmlTypeCode.Float);
            ValueCPRule cpRule45 = new ValueCPRule(valueActualObject45, valueExpectedObject45, PrimitiveTypeCP.EqualTo, "=", false);

            // Checkpoint 46
            IVTDGetter actualValueGetter46 = new VTDXPathGetter(new VTDPropertyInfoBase("OutputEnvelope", "/*[local-name(.)='Envelope'][1]/*[local-name(.)='Body'][1]/*[local-name(.)='GetFlightsResponse'][1]/*[local-name(.)='GetFlightsResult'][1]/*[local-name(.)='Flight'][7]/*[local-name(.)='Airline'][1]"), XmlTypeCode.String, false);
            IVTDSetter actualValueSetter46 = new VTDCheckpointSetter(XmlTypeCode.String);
            BindDirection actualBindDirection46 = new BindDirection(_flow.StServiceCallActivity4, actualValueGetter46, actualValueSetter46);
            CpValObj valueActualObject46 = new CpValObj(actualBindDirection46, XmlTypeCode.String, false);
            CpValObj valueExpectedObject46 = new CpValObj("AA", XmlTypeCode.String);
            ValueCPRule cpRule46 = new ValueCPRule(valueActualObject46, valueExpectedObject46, StringCP.EqualTo, "=", false);

            // Checkpoint 47
            IVTDGetter actualValueGetter47 = new VTDXPathGetter(new VTDPropertyInfoBase("OutputEnvelope", "/*[local-name(.)='Envelope'][1]/*[local-name(.)='Body'][1]/*[local-name(.)='GetFlightsResponse'][1]/*[local-name(.)='GetFlightsResult'][1]/*[local-name(.)='Flight'][7]/*[local-name(.)='ArrivalCity'][1]"), XmlTypeCode.String, false);
            IVTDSetter actualValueSetter47 = new VTDCheckpointSetter(XmlTypeCode.String);
            BindDirection actualBindDirection47 = new BindDirection(_flow.StServiceCallActivity4, actualValueGetter47, actualValueSetter47);
            CpValObj valueActualObject47 = new CpValObj(actualBindDirection47, XmlTypeCode.String, false);
            CpValObj valueExpectedObject47 = new CpValObj("Frankfurt", XmlTypeCode.String);
            ValueCPRule cpRule47 = new ValueCPRule(valueActualObject47, valueExpectedObject47, StringCP.EqualTo, "=", false);

            // Checkpoint 48
            IVTDGetter actualValueGetter48 = new VTDXPathGetter(new VTDPropertyInfoBase("OutputEnvelope", "/*[local-name(.)='Envelope'][1]/*[local-name(.)='Body'][1]/*[local-name(.)='GetFlightsResponse'][1]/*[local-name(.)='GetFlightsResult'][1]/*[local-name(.)='Flight'][7]/*[local-name(.)='ArrivalTime'][1]"), XmlTypeCode.String, false);
            IVTDSetter actualValueSetter48 = new VTDCheckpointSetter(XmlTypeCode.String);
            BindDirection actualBindDirection48 = new BindDirection(_flow.StServiceCallActivity4, actualValueGetter48, actualValueSetter48);
            CpValObj valueActualObject48 = new CpValObj(actualBindDirection48, XmlTypeCode.String, false);
            CpValObj valueExpectedObject48 = new CpValObj("03:57 PM", XmlTypeCode.String);
            ValueCPRule cpRule48 = new ValueCPRule(valueActualObject48, valueExpectedObject48, StringCP.EqualTo, "=", false);

            // Checkpoint 49
            IVTDGetter actualValueGetter49 = new VTDXPathGetter(new VTDPropertyInfoBase("OutputEnvelope", "/*[local-name(.)='Envelope'][1]/*[local-name(.)='Body'][1]/*[local-name(.)='GetFlightsResponse'][1]/*[local-name(.)='GetFlightsResult'][1]/*[local-name(.)='Flight'][7]/*[local-name(.)='DepartureCity'][1]"), XmlTypeCode.String, false);
            IVTDSetter actualValueSetter49 = new VTDCheckpointSetter(XmlTypeCode.String);
            BindDirection actualBindDirection49 = new BindDirection(_flow.StServiceCallActivity4, actualValueGetter49, actualValueSetter49);
            CpValObj valueActualObject49 = new CpValObj(actualBindDirection49, XmlTypeCode.String, false);
            CpValObj valueExpectedObject49 = new CpValObj("Denver", XmlTypeCode.String);
            ValueCPRule cpRule49 = new ValueCPRule(valueActualObject49, valueExpectedObject49, StringCP.EqualTo, "=", false);

            // Checkpoint 50
            IVTDGetter actualValueGetter50 = new VTDXPathGetter(new VTDPropertyInfoBase("OutputEnvelope", "/*[local-name(.)='Envelope'][1]/*[local-name(.)='Body'][1]/*[local-name(.)='GetFlightsResponse'][1]/*[local-name(.)='GetFlightsResult'][1]/*[local-name(.)='Flight'][7]/*[local-name(.)='DepartureTime'][1]"), XmlTypeCode.String, false);
            IVTDSetter actualValueSetter50 = new VTDCheckpointSetter(XmlTypeCode.String);
            BindDirection actualBindDirection50 = new BindDirection(_flow.StServiceCallActivity4, actualValueGetter50, actualValueSetter50);
            CpValObj valueActualObject50 = new CpValObj(actualBindDirection50, XmlTypeCode.String, false);
            CpValObj valueExpectedObject50 = new CpValObj("03:12 PM", XmlTypeCode.String);
            ValueCPRule cpRule50 = new ValueCPRule(valueActualObject50, valueExpectedObject50, StringCP.EqualTo, "=", false);

            // Checkpoint 51
            IVTDGetter actualValueGetter51 = new VTDXPathGetter(new VTDPropertyInfoBase("OutputEnvelope", "/*[local-name(.)='Envelope'][1]/*[local-name(.)='Body'][1]/*[local-name(.)='GetFlightsResponse'][1]/*[local-name(.)='GetFlightsResult'][1]/*[local-name(.)='Flight'][7]/*[local-name(.)='FlightNumber'][1]"), XmlTypeCode.Int, false);
            IVTDSetter actualValueSetter51 = new VTDCheckpointSetter(XmlTypeCode.Int);
            BindDirection actualBindDirection51 = new BindDirection(_flow.StServiceCallActivity4, actualValueGetter51, actualValueSetter51);
            CpValObj valueActualObject51 = new CpValObj(actualBindDirection51, XmlTypeCode.Int, false);
            CpValObj valueExpectedObject51 = new CpValObj("15841", XmlTypeCode.Int);
            ValueCPRule cpRule51 = new ValueCPRule(valueActualObject51, valueExpectedObject51, PrimitiveTypeCP.EqualTo, "=", false);

            // Checkpoint 52
            IVTDGetter actualValueGetter52 = new VTDXPathGetter(new VTDPropertyInfoBase("OutputEnvelope", "/*[local-name(.)='Envelope'][1]/*[local-name(.)='Body'][1]/*[local-name(.)='GetFlightsResponse'][1]/*[local-name(.)='GetFlightsResult'][1]/*[local-name(.)='Flight'][7]/*[local-name(.)='Price'][1]"), XmlTypeCode.Float, false);
            IVTDSetter actualValueSetter52 = new VTDCheckpointSetter(XmlTypeCode.Float);
            BindDirection actualBindDirection52 = new BindDirection(_flow.StServiceCallActivity4, actualValueGetter52, actualValueSetter52);
            CpValObj valueActualObject52 = new CpValObj(actualBindDirection52, XmlTypeCode.Float, false);
            CpValObj valueExpectedObject52 = new CpValObj("103", XmlTypeCode.Float);
            ValueCPRule cpRule52 = new ValueCPRule(valueActualObject52, valueExpectedObject52, PrimitiveTypeCP.EqualTo, "=", false);

            // Checkpoint 53
            IVTDGetter actualValueGetter53 = new VTDXPathGetter(new VTDPropertyInfoBase("OutputEnvelope", "/*[local-name(.)='Envelope'][1]/*[local-name(.)='Body'][1]/*[local-name(.)='GetFlightsResponse'][1]/*[local-name(.)='GetFlightsResult'][1]/*[local-name(.)='Flight'][8]/*[local-name(.)='Airline'][1]"), XmlTypeCode.String, false);
            IVTDSetter actualValueSetter53 = new VTDCheckpointSetter(XmlTypeCode.String);
            BindDirection actualBindDirection53 = new BindDirection(_flow.StServiceCallActivity4, actualValueGetter53, actualValueSetter53);
            CpValObj valueActualObject53 = new CpValObj(actualBindDirection53, XmlTypeCode.String, false);
            CpValObj valueExpectedObject53 = new CpValObj("AF", XmlTypeCode.String);
            ValueCPRule cpRule53 = new ValueCPRule(valueActualObject53, valueExpectedObject53, StringCP.EqualTo, "=", false);

            // Checkpoint 54
            IVTDGetter actualValueGetter54 = new VTDXPathGetter(new VTDPropertyInfoBase("OutputEnvelope", "/*[local-name(.)='Envelope'][1]/*[local-name(.)='Body'][1]/*[local-name(.)='GetFlightsResponse'][1]/*[local-name(.)='GetFlightsResult'][1]/*[local-name(.)='Flight'][8]/*[local-name(.)='ArrivalCity'][1]"), XmlTypeCode.String, false);
            IVTDSetter actualValueSetter54 = new VTDCheckpointSetter(XmlTypeCode.String);
            BindDirection actualBindDirection54 = new BindDirection(_flow.StServiceCallActivity4, actualValueGetter54, actualValueSetter54);
            CpValObj valueActualObject54 = new CpValObj(actualBindDirection54, XmlTypeCode.String, false);
            CpValObj valueExpectedObject54 = new CpValObj("Frankfurt", XmlTypeCode.String);
            ValueCPRule cpRule54 = new ValueCPRule(valueActualObject54, valueExpectedObject54, StringCP.EqualTo, "=", false);

            // Checkpoint 55
            IVTDGetter actualValueGetter55 = new VTDXPathGetter(new VTDPropertyInfoBase("OutputEnvelope", "/*[local-name(.)='Envelope'][1]/*[local-name(.)='Body'][1]/*[local-name(.)='GetFlightsResponse'][1]/*[local-name(.)='GetFlightsResult'][1]/*[local-name(.)='Flight'][8]/*[local-name(.)='ArrivalTime'][1]"), XmlTypeCode.String, false);
            IVTDSetter actualValueSetter55 = new VTDCheckpointSetter(XmlTypeCode.String);
            BindDirection actualBindDirection55 = new BindDirection(_flow.StServiceCallActivity4, actualValueGetter55, actualValueSetter55);
            CpValObj valueActualObject55 = new CpValObj(actualBindDirection55, XmlTypeCode.String, false);
            CpValObj valueExpectedObject55 = new CpValObj("06:42 PM", XmlTypeCode.String);
            ValueCPRule cpRule55 = new ValueCPRule(valueActualObject55, valueExpectedObject55, StringCP.EqualTo, "=", false);

            // Checkpoint 56
            IVTDGetter actualValueGetter56 = new VTDXPathGetter(new VTDPropertyInfoBase("OutputEnvelope", "/*[local-name(.)='Envelope'][1]/*[local-name(.)='Body'][1]/*[local-name(.)='GetFlightsResponse'][1]/*[local-name(.)='GetFlightsResult'][1]/*[local-name(.)='Flight'][8]/*[local-name(.)='DepartureCity'][1]"), XmlTypeCode.String, false);
            IVTDSetter actualValueSetter56 = new VTDCheckpointSetter(XmlTypeCode.String);
            BindDirection actualBindDirection56 = new BindDirection(_flow.StServiceCallActivity4, actualValueGetter56, actualValueSetter56);
            CpValObj valueActualObject56 = new CpValObj(actualBindDirection56, XmlTypeCode.String, false);
            CpValObj valueExpectedObject56 = new CpValObj("Denver", XmlTypeCode.String);
            ValueCPRule cpRule56 = new ValueCPRule(valueActualObject56, valueExpectedObject56, StringCP.EqualTo, "=", false);

            // Checkpoint 57
            IVTDGetter actualValueGetter57 = new VTDXPathGetter(new VTDPropertyInfoBase("OutputEnvelope", "/*[local-name(.)='Envelope'][1]/*[local-name(.)='Body'][1]/*[local-name(.)='GetFlightsResponse'][1]/*[local-name(.)='GetFlightsResult'][1]/*[local-name(.)='Flight'][8]/*[local-name(.)='DepartureTime'][1]"), XmlTypeCode.String, false);
            IVTDSetter actualValueSetter57 = new VTDCheckpointSetter(XmlTypeCode.String);
            BindDirection actualBindDirection57 = new BindDirection(_flow.StServiceCallActivity4, actualValueGetter57, actualValueSetter57);
            CpValObj valueActualObject57 = new CpValObj(actualBindDirection57, XmlTypeCode.String, false);
            CpValObj valueExpectedObject57 = new CpValObj("03:12 PM", XmlTypeCode.String);
            ValueCPRule cpRule57 = new ValueCPRule(valueActualObject57, valueExpectedObject57, StringCP.EqualTo, "=", false);

            // Checkpoint 58
            IVTDGetter actualValueGetter58 = new VTDXPathGetter(new VTDPropertyInfoBase("OutputEnvelope", "/*[local-name(.)='Envelope'][1]/*[local-name(.)='Body'][1]/*[local-name(.)='GetFlightsResponse'][1]/*[local-name(.)='GetFlightsResult'][1]/*[local-name(.)='Flight'][8]/*[local-name(.)='FlightNumber'][1]"), XmlTypeCode.Int, false);
            IVTDSetter actualValueSetter58 = new VTDCheckpointSetter(XmlTypeCode.Int);
            BindDirection actualBindDirection58 = new BindDirection(_flow.StServiceCallActivity4, actualValueGetter58, actualValueSetter58);
            CpValObj valueActualObject58 = new CpValObj(actualBindDirection58, XmlTypeCode.Int, false);
            CpValObj valueExpectedObject58 = new CpValObj("15842", XmlTypeCode.Int);
            ValueCPRule cpRule58 = new ValueCPRule(valueActualObject58, valueExpectedObject58, PrimitiveTypeCP.EqualTo, "=", false);

            // Checkpoint 59
            IVTDGetter actualValueGetter59 = new VTDXPathGetter(new VTDPropertyInfoBase("OutputEnvelope", "/*[local-name(.)='Envelope'][1]/*[local-name(.)='Body'][1]/*[local-name(.)='GetFlightsResponse'][1]/*[local-name(.)='GetFlightsResult'][1]/*[local-name(.)='Flight'][8]/*[local-name(.)='Price'][1]"), XmlTypeCode.Float, false);
            IVTDSetter actualValueSetter59 = new VTDCheckpointSetter(XmlTypeCode.Float);
            BindDirection actualBindDirection59 = new BindDirection(_flow.StServiceCallActivity4, actualValueGetter59, actualValueSetter59);
            CpValObj valueActualObject59 = new CpValObj(actualBindDirection59, XmlTypeCode.Float, false);
            CpValObj valueExpectedObject59 = new CpValObj("174.47", XmlTypeCode.Float);
            ValueCPRule cpRule59 = new ValueCPRule(valueActualObject59, valueExpectedObject59, PrimitiveTypeCP.EqualTo, "=", false);

            // Checkpoint 60
            IVTDGetter actualValueGetter60 = new VTDXPathGetter(new VTDPropertyInfoBase("OutputEnvelope", "/*[local-name(.)='Envelope'][1]/*[local-name(.)='Body'][1]/*[local-name(.)='GetFlightsResponse'][1]/*[local-name(.)='GetFlightsResult'][1]/*[local-name(.)='Flight'][9]/*[local-name(.)='Airline'][1]"), XmlTypeCode.String, false);
            IVTDSetter actualValueSetter60 = new VTDCheckpointSetter(XmlTypeCode.String);
            BindDirection actualBindDirection60 = new BindDirection(_flow.StServiceCallActivity4, actualValueGetter60, actualValueSetter60);
            CpValObj valueActualObject60 = new CpValObj(actualBindDirection60, XmlTypeCode.String, false);
            CpValObj valueExpectedObject60 = new CpValObj("NW", XmlTypeCode.String);
            ValueCPRule cpRule60 = new ValueCPRule(valueActualObject60, valueExpectedObject60, StringCP.EqualTo, "=", false);

            // Checkpoint 61
            IVTDGetter actualValueGetter61 = new VTDXPathGetter(new VTDPropertyInfoBase("OutputEnvelope", "/*[local-name(.)='Envelope'][1]/*[local-name(.)='Body'][1]/*[local-name(.)='GetFlightsResponse'][1]/*[local-name(.)='GetFlightsResult'][1]/*[local-name(.)='Flight'][9]/*[local-name(.)='ArrivalCity'][1]"), XmlTypeCode.String, false);
            IVTDSetter actualValueSetter61 = new VTDCheckpointSetter(XmlTypeCode.String);
            BindDirection actualBindDirection61 = new BindDirection(_flow.StServiceCallActivity4, actualValueGetter61, actualValueSetter61);
            CpValObj valueActualObject61 = new CpValObj(actualBindDirection61, XmlTypeCode.String, false);
            CpValObj valueExpectedObject61 = new CpValObj("Frankfurt", XmlTypeCode.String);
            ValueCPRule cpRule61 = new ValueCPRule(valueActualObject61, valueExpectedObject61, StringCP.EqualTo, "=", false);

            // Checkpoint 62
            IVTDGetter actualValueGetter62 = new VTDXPathGetter(new VTDPropertyInfoBase("OutputEnvelope", "/*[local-name(.)='Envelope'][1]/*[local-name(.)='Body'][1]/*[local-name(.)='GetFlightsResponse'][1]/*[local-name(.)='GetFlightsResult'][1]/*[local-name(.)='Flight'][9]/*[local-name(.)='ArrivalTime'][1]"), XmlTypeCode.String, false);
            IVTDSetter actualValueSetter62 = new VTDCheckpointSetter(XmlTypeCode.String);
            BindDirection actualBindDirection62 = new BindDirection(_flow.StServiceCallActivity4, actualValueGetter62, actualValueSetter62);
            CpValObj valueActualObject62 = new CpValObj(actualBindDirection62, XmlTypeCode.String, false);
            CpValObj valueExpectedObject62 = new CpValObj("02:53 PM", XmlTypeCode.String);
            ValueCPRule cpRule62 = new ValueCPRule(valueActualObject62, valueExpectedObject62, StringCP.EqualTo, "=", false);

            // Checkpoint 63
            IVTDGetter actualValueGetter63 = new VTDXPathGetter(new VTDPropertyInfoBase("OutputEnvelope", "/*[local-name(.)='Envelope'][1]/*[local-name(.)='Body'][1]/*[local-name(.)='GetFlightsResponse'][1]/*[local-name(.)='GetFlightsResult'][1]/*[local-name(.)='Flight'][9]/*[local-name(.)='DepartureCity'][1]"), XmlTypeCode.String, false);
            IVTDSetter actualValueSetter63 = new VTDCheckpointSetter(XmlTypeCode.String);
            BindDirection actualBindDirection63 = new BindDirection(_flow.StServiceCallActivity4, actualValueGetter63, actualValueSetter63);
            CpValObj valueActualObject63 = new CpValObj(actualBindDirection63, XmlTypeCode.String, false);
            CpValObj valueExpectedObject63 = new CpValObj("Denver", XmlTypeCode.String);
            ValueCPRule cpRule63 = new ValueCPRule(valueActualObject63, valueExpectedObject63, StringCP.EqualTo, "=", false);

            // Checkpoint 64
            IVTDGetter actualValueGetter64 = new VTDXPathGetter(new VTDPropertyInfoBase("OutputEnvelope", "/*[local-name(.)='Envelope'][1]/*[local-name(.)='Body'][1]/*[local-name(.)='GetFlightsResponse'][1]/*[local-name(.)='GetFlightsResult'][1]/*[local-name(.)='Flight'][9]/*[local-name(.)='DepartureTime'][1]"), XmlTypeCode.String, false);
            IVTDSetter actualValueSetter64 = new VTDCheckpointSetter(XmlTypeCode.String);
            BindDirection actualBindDirection64 = new BindDirection(_flow.StServiceCallActivity4, actualValueGetter64, actualValueSetter64);
            CpValObj valueActualObject64 = new CpValObj(actualBindDirection64, XmlTypeCode.String, false);
            CpValObj valueExpectedObject64 = new CpValObj("02:09 PM", XmlTypeCode.String);
            ValueCPRule cpRule64 = new ValueCPRule(valueActualObject64, valueExpectedObject64, StringCP.EqualTo, "=", false);

            // Checkpoint 65
            IVTDGetter actualValueGetter65 = new VTDXPathGetter(new VTDPropertyInfoBase("OutputEnvelope", "/*[local-name(.)='Envelope'][1]/*[local-name(.)='Body'][1]/*[local-name(.)='GetFlightsResponse'][1]/*[local-name(.)='GetFlightsResult'][1]/*[local-name(.)='Flight'][9]/*[local-name(.)='FlightNumber'][1]"), XmlTypeCode.Int, false);
            IVTDSetter actualValueSetter65 = new VTDCheckpointSetter(XmlTypeCode.Int);
            BindDirection actualBindDirection65 = new BindDirection(_flow.StServiceCallActivity4, actualValueGetter65, actualValueSetter65);
            CpValObj valueActualObject65 = new CpValObj(actualBindDirection65, XmlTypeCode.Int, false);
            CpValObj valueExpectedObject65 = new CpValObj("15932", XmlTypeCode.Int);
            ValueCPRule cpRule65 = new ValueCPRule(valueActualObject65, valueExpectedObject65, PrimitiveTypeCP.EqualTo, "=", false);

            // Checkpoint 66
            IVTDGetter actualValueGetter66 = new VTDXPathGetter(new VTDPropertyInfoBase("OutputEnvelope", "/*[local-name(.)='Envelope'][1]/*[local-name(.)='Body'][1]/*[local-name(.)='GetFlightsResponse'][1]/*[local-name(.)='GetFlightsResult'][1]/*[local-name(.)='Flight'][9]/*[local-name(.)='Price'][1]"), XmlTypeCode.Float, false);
            IVTDSetter actualValueSetter66 = new VTDCheckpointSetter(XmlTypeCode.Float);
            BindDirection actualBindDirection66 = new BindDirection(_flow.StServiceCallActivity4, actualValueGetter66, actualValueSetter66);
            CpValObj valueActualObject66 = new CpValObj(actualBindDirection66, XmlTypeCode.Float, false);
            CpValObj valueExpectedObject66 = new CpValObj("179.47", XmlTypeCode.Float);
            ValueCPRule cpRule66 = new ValueCPRule(valueActualObject66, valueExpectedObject66, PrimitiveTypeCP.EqualTo, "=", false);

            ArrayElementCPRule arrayElementCPRule1 = new ArrayElementCPRule();
            ArrayBaseCPRule arrayFixedCpRule1 = new ArrayFixedCPRule("/*[local-name(.)='Envelope'][1]/*[local-name(.)='Body'][1]/*[local-name(.)='GetFlightsResponse'][1]/*[local-name(.)='GetFlightsResult'][1]/*[local-name(.)='Flight']", HandlerType.XML);
            ArrayElementCPRule arrayElementCPRule2 = new ArrayElementCPRule();
            ArrayElementCPRule arrayElementCPRule3 = new ArrayElementCPRule();
            ArrayElementCPRule arrayElementCPRule4 = new ArrayElementCPRule();
            ArrayElementCPRule arrayElementCPRule5 = new ArrayElementCPRule();
            ArrayElementCPRule arrayElementCPRule6 = new ArrayElementCPRule();
            ArrayElementCPRule arrayElementCPRule7 = new ArrayElementCPRule();
            ArrayElementCPRule arrayElementCPRule8 = new ArrayElementCPRule();
            ArrayElementCPRule arrayElementCPRule9 = new ArrayElementCPRule();
            arrayElementCPRule1.AddRule(cpRule4);
            arrayElementCPRule1.AddRule(cpRule5);
            arrayElementCPRule1.AddRule(cpRule6);
            arrayElementCPRule1.AddRule(cpRule7);
            arrayElementCPRule1.AddRule(cpRule8);
            arrayElementCPRule1.AddRule(cpRule9);
            arrayElementCPRule1.AddRule(cpRule10);
            arrayFixedCpRule1.AddRule(arrayElementCPRule1);
            arrayFixedCpRule1.AddRule(arrayElementCPRule2);
            arrayFixedCpRule1.AddRule(arrayElementCPRule3);
            arrayFixedCpRule1.AddRule(arrayElementCPRule4);
            arrayFixedCpRule1.AddRule(arrayElementCPRule5);
            arrayFixedCpRule1.AddRule(arrayElementCPRule6);
            arrayFixedCpRule1.AddRule(arrayElementCPRule7);
            arrayFixedCpRule1.AddRule(arrayElementCPRule8);
            arrayFixedCpRule1.AddRule(arrayElementCPRule9);
            arrayElementCPRule2.AddRule(cpRule11);
            arrayElementCPRule2.AddRule(cpRule12);
            arrayElementCPRule2.AddRule(cpRule13);
            arrayElementCPRule2.AddRule(cpRule14);
            arrayElementCPRule2.AddRule(cpRule15);
            arrayElementCPRule2.AddRule(cpRule16);
            arrayElementCPRule2.AddRule(cpRule17);
            arrayElementCPRule3.AddRule(cpRule18);
            arrayElementCPRule3.AddRule(cpRule19);
            arrayElementCPRule3.AddRule(cpRule20);
            arrayElementCPRule3.AddRule(cpRule21);
            arrayElementCPRule3.AddRule(cpRule22);
            arrayElementCPRule3.AddRule(cpRule23);
            arrayElementCPRule3.AddRule(cpRule24);
            arrayElementCPRule4.AddRule(cpRule25);
            arrayElementCPRule4.AddRule(cpRule26);
            arrayElementCPRule4.AddRule(cpRule27);
            arrayElementCPRule4.AddRule(cpRule28);
            arrayElementCPRule4.AddRule(cpRule29);
            arrayElementCPRule4.AddRule(cpRule30);
            arrayElementCPRule4.AddRule(cpRule31);
            arrayElementCPRule5.AddRule(cpRule32);
            arrayElementCPRule5.AddRule(cpRule33);
            arrayElementCPRule5.AddRule(cpRule34);
            arrayElementCPRule5.AddRule(cpRule35);
            arrayElementCPRule5.AddRule(cpRule36);
            arrayElementCPRule5.AddRule(cpRule37);
            arrayElementCPRule5.AddRule(cpRule38);
            arrayElementCPRule6.AddRule(cpRule39);
            arrayElementCPRule6.AddRule(cpRule40);
            arrayElementCPRule6.AddRule(cpRule41);
            arrayElementCPRule6.AddRule(cpRule42);
            arrayElementCPRule6.AddRule(cpRule43);
            arrayElementCPRule6.AddRule(cpRule44);
            arrayElementCPRule6.AddRule(cpRule45);
            arrayElementCPRule7.AddRule(cpRule46);
            arrayElementCPRule7.AddRule(cpRule47);
            arrayElementCPRule7.AddRule(cpRule48);
            arrayElementCPRule7.AddRule(cpRule49);
            arrayElementCPRule7.AddRule(cpRule50);
            arrayElementCPRule7.AddRule(cpRule51);
            arrayElementCPRule7.AddRule(cpRule52);
            arrayElementCPRule8.AddRule(cpRule53);
            arrayElementCPRule8.AddRule(cpRule54);
            arrayElementCPRule8.AddRule(cpRule55);
            arrayElementCPRule8.AddRule(cpRule56);
            arrayElementCPRule8.AddRule(cpRule57);
            arrayElementCPRule8.AddRule(cpRule58);
            arrayElementCPRule8.AddRule(cpRule59);
            arrayElementCPRule9.AddRule(cpRule60);
            arrayElementCPRule9.AddRule(cpRule61);
            arrayElementCPRule9.AddRule(cpRule62);
            arrayElementCPRule9.AddRule(cpRule63);
            arrayElementCPRule9.AddRule(cpRule64);
            arrayElementCPRule9.AddRule(cpRule65);
            arrayElementCPRule9.AddRule(cpRule66);
            activity.AddCheckpointRule(arrayFixedCpRule1);
        }
    }
}
